### ISSUE TITLE
Add ContentType html.

### ISSUE THREAD

**Issue by osolomin90** [ryparker/jest-circus-allure-environment#153]
## Is your feature request related to a problem? Please describe

In Java world allure allows attach html, I use it to attach Email body from my tests, looks next 
'Allure.addAttachment(mail+" - " + templateId, "text/html", message.html().body(), "html");'
but I can not use this feature with jest-circus-allure-environment.

## Describe the solution you'd like

Extend existing ContentType enum with new type/extension.

**Comment by ryparker** [comment]
[Added HTML to the `ContentType` type.](https://github.com/ryparker/jest-circus-allure-environment/blob/93c9925d2f702f02ab8a9a99fcfd52c0438a91e3/src/types.ts#L4)
