### ISSUE TITLE
In Jest 27 expectation result matcher.message no longer a function

### ISSUE THREAD

**Issue by Rendez** [ryparker/jest-circus-allure-environment#173]
We saw this error on our CI: `TypeError: error.matcherResult.message is not a function`

I turns out that Circus.Event's` event.test.errors[0].matcherResult.message` [is no longer a function in Jest 27](https://github.com/facebook/jest/commit/c2f152d9da6298a97a85233b2e754a1cbe7e0a61). The breaking change just got introduced, can we handle this by checking if it's a function?

ps: I know that 27 isn't yet release, but we're using it because it brings full TS support for jest envs and other stuff, and it seems short to the release date.

**Comment by ryparker** [comment]
Released in https://github.com/ryparker/jest-circus-allure-environment/releases/tag/v1.0.3
