### ISSUE TITLE
support for custom attachment content types

### ISSUE THREAD

**Issue by isolationdesolation** [ryparker/jest-circus-allure-environment#175]
Hi! I have found that jest-circus-allure-environment does not support custom attachment types, like it is implemented here https://github.com/allure-framework/allure-js/commit/dbce900e0dfaa50a70a0715f99b8d5824b956432 . 
It would be nice to have such an opportunity to add custom attachments (for example, i need "imagediff/json" to use screendiff allure plugin in their test management system; or maybe some other content type that other test management system may require - string as abstract type can handle this unexpected proposed requirements): 

> allure.attachment(
>   name: string,
>   content: Buffer | string,
>   type: ContentType | string
> );

:^)

**Comment by ryparker** [comment]
Hey thanks for opening an issue for this 😄. The implementation you proposed sounds like a good solution and could also be used to solve another issue (https://github.com/ryparker/jest-circus-allure-environment/issues/155)

I'll take a look into this and get back to you by the weekend.
