### ISSUE TITLE
crypto.js dependency no longer needed

### ISSUE THREAD

**Issue by Rendez** [ryparker/jest-circus-allure-environment#176]
Hi, I'm seeing the next warning from `yarn install`:

```sh
warning jest-circus-allure-environment > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

Seems like Node 12 (which is specified on package.json's engines section) already has crypto.

**Comment by ryparker** [comment]
Good catch. Should be resolved in [v1.1.0](https://github.com/ryparker/jest-circus-allure-environment/releases/tag/v1.1.0)
