### ISSUE TITLE
Jest testEnvironment is not array

### ISSUE THREAD

**Issue by d-shch** [ryparker/jest-circus-allure-environment#9]
Hi!

I noticed one mini bug in readme in step **Update jest.config.js** 

```
Option "testEnvironment" must be of type:
    string
  but instead received:
    array

  Example:
  {
    "testEnvironment": "jest-circus-allure-environment"
  }
```

And I have one question :-) How add reporter to my project if I already have custom test environment?

**Comment by ryparker** [comment]
Nice catch, i'll fix the README. Thank you!

> How add reporter to my project if I already have custom test environment?

If you already have a custom Jest environment than I believe you only have two options:
- Combine the environments by creating your own Jest environment. I have a [template repo available here](https://github.com/ryparker/jest-circus-environment-template), for creating custom Jest-Circus environments if you're interested.
- Or you could choose stick with one environment and specify a different environment for your test files using docBlock pragmas. Documentation for that is [available here](https://jestjs.io/docs/en/configuration#testenvironment-string).
Example:
```js
/**
 * @jest-environment jsdom
 */

test('use jsdom in this test file', () => {
  const element = document.createElement('div');
  expect(element).not.toBeNull();
});
```

**Comment by d-shch** [comment]
Ok, thanks for response, i will try combine the environments
